### PR TITLE
827 refinements and test

### LINKED ISSUE #827: Rate Limiting blocks everything after a while
**Describe the bug**

I have a set up where I use Couper as an egress Gateway to implement a client-side rate limiting.

(I have a group of services that use the same rate-limited upstream API. The services run independently, so I wanted to have central exit point where I can count/throttle requests.)

Because the upstream is very rigid, I use a connection pool size of 1 and a rate limiter.

At first it works fine. Requests are throttled but succeed after queueing for a bit. But it can happen that too many requests pile up and the queue get longer. Sometimes that leads to requests being canceled by the HTTP clients (because they also have their timeouts).

After some time, Couper is in a state where all incoming requests are stuck in an endless block/wait queue. Even if there weren't any requests over a couple of minutes (the rate limiter window is a minute), all new requests wait forever until they timeout.

I cannot reproduce it yet, but it happens again and again. I have to restart Couper to get out of it.

**To Reproduce**

?

1. Which Couper version? Run `couper version` or `docker run coupergateway/couper version`

1.12.1 and edge

2. Provide your configuration file `*.hcl`. Remove sensitive data.

```hcl
definitions {
  backend "upstream" {
    origin = env.ORIGIN
    max_connections = env.MAX_CONNECTIIONS
    set_request_headers = {
      authorization = request.headers.authorization
    }
    beta_rate_limit {
      mode = "wait"
      period = "60s"
      per_period = env.REQUESTS_PER_MINUTE
      period_window = "fixed"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by malud**
Closes #827 

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

### CODE REVIEW

File: handler/ratelimit/limiter.go [hunk 1]
```diff
@@ -133,18 +106,26 @@ func (l *Limiter) checkCapacity() (mode int, t time.Duration) {
...
 			if multiplicator > 0 {
-				rl.periodStart = rl.periodStart.Add(time.Duration(rl.period.Nanoseconds() * multiplicator))
-				rl.count = 0
+				currentPeriod = currentPeriod.Add(time.Duration(rl.period.Nanoseconds() * multiplicator))
+				rl.setPeriodStart(currentPeriod)
+				rl.count.Store(0)
 			}
 
-			if rl.count >= rl.perPeriod {
+			//fmt.Printf("Period start: %v, Current time: %v, Count: %d\n", currentPeriod, now, rl.count.Load()) // debug
```
Comment (johakoch) [inline handler/ratelimit/limiter.go:124]: Can this comment be removed?

File: handler/ratelimit/limiter.go [hunk 2]
```diff
@@ -77,51 +72,29 @@ func (l *Limiter) slowTripper() {
...
 
-				l.mu.Unlock()
-
 				// Do not wait for the response...
 				go func() {
 					trip.res, trip.err = l.transport.RoundTrip(trip.req)
-
-					if trip.res != nil && trip.res.StatusCode == http.StatusTooManyRequests {
-						trip.err = errors.BetaBackendRateLimitExceeded.With(trip.err)
-					}
```
Comment (filex) [inline handler/ratelimit/limiter.go:123]: this is a behaviour change. An upstream `429` (which wasn't necessarily throttled at all) currently results in a _couper error_. While that still results in a status `429` response to the client, any couper error handler will not trigger anymore. Usually this will mean that the upstream response body is passed through `proxy` endpoints - instead of the default couper error page.

I still think that this current behaviour is unexpected. So I'm fine with the change. but we should add a _change_ type changelog entry.

File: handler/ratelimit/limiter.go [hunk 3]
```diff
@@ -125,22 +117,24 @@ func (l *Limiter) checkCapacity() (mode int, t time.Duration) {
...
 			// Update current period.
-			multiplicator := ((now.UnixNano() - rl.periodStart.UnixNano()) / int64(time.Nanosecond)) / rl.period.Nanoseconds()
+			currentPeriod := rl.getPeriodStart()
+			multiplicator := ((now.UnixNano() - currentPeriod.UnixNano()) / int64(time.Nanosecond)) / rl.period.Nanoseconds()
 			if multiplicator > 0 {
-				rl.periodStart = rl.periodStart.Add(time.Duration(rl.period.Nanoseconds() * multiplicator))
-				rl.count = 0
+				currentPeriod = currentPeriod.Add(time.Duration(rl.period.Nanoseconds() * multiplicator))
+				rl.setPeriodStart(currentPeriod)
+				rl.count.Store(0)
```
Comment (filex) [inline handler/ratelimit/limiter.go:121]: shouldn't we move this into `setPeriodStart()` (or maybe rename that to `resetPeriod()`. This way the two atomic values are not in a shared lock and multiple requests could override the count leading to some "free" requests.

Or is this prohibited by the non-buffered channel that will ever only let one request drip through the limiter (before fanning-out to the backend)?

Comment (filex) [reply handler/ratelimit/limiter.go:121]: if so (serialization through channel), why do we have to use locks at all? If we have multiple rate-limiters in one backend they wouldn't share the same count and periodStart.

Comment (malud) [reply handler/ratelimit/limiter.go:121]: Yes, it's actually serialized through channels. The initial change was to move the lock for all limiters (range) to specific ones, but this doesn't make sense either. I'll remove the lock too.

**Review by filex — APPROVED** [review]
